// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/usecase/usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	app "github.com/MisterMaks/go-yandex-shortener/internal/app"
	gomock "github.com/golang/mock/gomock"
)

// MockAppRepoInterface is a mock of AppRepoInterface interface.
type MockAppRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAppRepoInterfaceMockRecorder
}

// MockAppRepoInterfaceMockRecorder is the mock recorder for MockAppRepoInterface.
type MockAppRepoInterfaceMockRecorder struct {
	mock *MockAppRepoInterface
}

// NewMockAppRepoInterface creates a new mock instance.
func NewMockAppRepoInterface(ctrl *gomock.Controller) *MockAppRepoInterface {
	mock := &MockAppRepoInterface{ctrl: ctrl}
	mock.recorder = &MockAppRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppRepoInterface) EXPECT() *MockAppRepoInterfaceMockRecorder {
	return m.recorder
}

// CheckIDExistence mocks base method.
func (m *MockAppRepoInterface) CheckIDExistence(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIDExistence", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIDExistence indicates an expected call of CheckIDExistence.
func (mr *MockAppRepoInterfaceMockRecorder) CheckIDExistence(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIDExistence", reflect.TypeOf((*MockAppRepoInterface)(nil).CheckIDExistence), ctx, id)
}

// Close mocks base method.
func (m *MockAppRepoInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAppRepoInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAppRepoInterface)(nil).Close))
}

// DeleteUserURLs mocks base method.
func (m *MockAppRepoInterface) DeleteUserURLs(ctx context.Context, urls []*app.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserURLs", ctx, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserURLs indicates an expected call of DeleteUserURLs.
func (mr *MockAppRepoInterfaceMockRecorder) DeleteUserURLs(ctx, urls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserURLs", reflect.TypeOf((*MockAppRepoInterface)(nil).DeleteUserURLs), ctx, urls)
}

// GetCountURLs mocks base method.
func (m *MockAppRepoInterface) GetCountURLs(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountURLs", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountURLs indicates an expected call of GetCountURLs.
func (mr *MockAppRepoInterfaceMockRecorder) GetCountURLs(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountURLs", reflect.TypeOf((*MockAppRepoInterface)(nil).GetCountURLs), ctx)
}

// GetOrCreateURL mocks base method.
func (m *MockAppRepoInterface) GetOrCreateURL(ctx context.Context, id, rawURL string, userID uint) (*app.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateURL", ctx, id, rawURL, userID)
	ret0, _ := ret[0].(*app.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateURL indicates an expected call of GetOrCreateURL.
func (mr *MockAppRepoInterfaceMockRecorder) GetOrCreateURL(ctx, id, rawURL, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateURL", reflect.TypeOf((*MockAppRepoInterface)(nil).GetOrCreateURL), ctx, id, rawURL, userID)
}

// GetOrCreateURLs mocks base method.
func (m *MockAppRepoInterface) GetOrCreateURLs(ctx context.Context, urls []*app.URL) ([]*app.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateURLs", ctx, urls)
	ret0, _ := ret[0].([]*app.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateURLs indicates an expected call of GetOrCreateURLs.
func (mr *MockAppRepoInterfaceMockRecorder) GetOrCreateURLs(ctx, urls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateURLs", reflect.TypeOf((*MockAppRepoInterface)(nil).GetOrCreateURLs), ctx, urls)
}

// GetURL mocks base method.
func (m *MockAppRepoInterface) GetURL(ctx context.Context, id string) (*app.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, id)
	ret0, _ := ret[0].(*app.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockAppRepoInterfaceMockRecorder) GetURL(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockAppRepoInterface)(nil).GetURL), ctx, id)
}

// GetUserURLs mocks base method.
func (m *MockAppRepoInterface) GetUserURLs(ctx context.Context, userID uint) ([]*app.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", ctx, userID)
	ret0, _ := ret[0].([]*app.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLs indicates an expected call of GetUserURLs.
func (mr *MockAppRepoInterfaceMockRecorder) GetUserURLs(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockAppRepoInterface)(nil).GetUserURLs), ctx, userID)
}

// MockUserUsecaseInterface is a mock of UserUsecaseInterface interface.
type MockUserUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserUsecaseInterfaceMockRecorder
}

// MockUserUsecaseInterfaceMockRecorder is the mock recorder for MockUserUsecaseInterface.
type MockUserUsecaseInterfaceMockRecorder struct {
	mock *MockUserUsecaseInterface
}

// NewMockUserUsecaseInterface creates a new mock instance.
func NewMockUserUsecaseInterface(ctrl *gomock.Controller) *MockUserUsecaseInterface {
	mock := &MockUserUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockUserUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUsecaseInterface) EXPECT() *MockUserUsecaseInterfaceMockRecorder {
	return m.recorder
}

// GetCountUsers mocks base method.
func (m *MockUserUsecaseInterface) GetCountUsers(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountUsers", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountUsers indicates an expected call of GetCountUsers.
func (mr *MockUserUsecaseInterfaceMockRecorder) GetCountUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountUsers", reflect.TypeOf((*MockUserUsecaseInterface)(nil).GetCountUsers), ctx)
}
