definitions:
  app.RequestBatchURL:
    properties:
      correlation_id:
        type: string
      original_url:
        type: string
    type: object
  app.ResponseBatchURL:
    properties:
      correlation_id:
        type: string
      short_url:
        type: string
    type: object
  app.ResponseUserURL:
    properties:
      original_url:
        type: string
      short_url:
        type: string
    type: object
  delivery.APIGetOrCreateURL.Request:
    properties:
      url:
        type: string
    type: object
  delivery.APIGetOrCreateURL.Response:
    properties:
      result:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    post:
      consumes:
      - text/plain
      parameters:
      - description: URL
        example: https://test.org
        in: body
        name: url
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "201":
          description: URL created
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "405":
          description: Method not allowed
          schema:
            type: string
        "409":
          description: URL exists
          schema:
            type: string
      summary: Get (if URL existed) or create URL
  /{url_id}:
    get:
      parameters:
      - description: URL ID
        example: qwerty
        in: path
        name: url_id
        required: true
        type: string
      produces:
      - text/html
      responses:
        "307":
          description: Redirect to original URL
          schema:
            type: body
        "400":
          description: Bad request
          schema:
            type: string
        "405":
          description: Method not allowed
          schema:
            type: string
        "410":
          description: Gone
          schema:
            type: string
      summary: Redirect to original URL
  /api/shorten:
    post:
      consumes:
      - application/json
      parameters:
      - description: URL
        in: body
        name: url
        required: true
        schema:
          $ref: '#/definitions/delivery.APIGetOrCreateURL.Request'
      produces:
      - application/json
      responses:
        "201":
          description: URL created
          schema:
            $ref: '#/definitions/delivery.APIGetOrCreateURL.Response'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "405":
          description: Method not allowed
          schema:
            type: string
        "409":
          description: URL exists
          schema:
            $ref: '#/definitions/delivery.APIGetOrCreateURL.Response'
      summary: Get (if URL existed) or create URL in JSON format
  /api/shorten/batch:
    post:
      consumes:
      - application/json
      parameters:
      - description: URL
        in: body
        name: url
        required: true
        schema:
          items:
            $ref: '#/definitions/app.RequestBatchURL'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: URLs created
          schema:
            items:
              $ref: '#/definitions/app.ResponseBatchURL'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "405":
          description: Method not allowed
          schema:
            type: string
      summary: Get (if URLs existed) or create URLs in JSON format
  /api/user/urls:
    delete:
      consumes:
      - application/json
      parameters:
      - description: URL IDs
        in: body
        name: url_ids
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - text/plain
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "405":
          description: Method not allowed
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Delete user URLs in JSON format
    get:
      produces:
      - application/json
      responses:
        "200":
          description: URLs created
          schema:
            items:
              $ref: '#/definitions/app.ResponseUserURL'
            type: array
        "204":
          description: No content
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "405":
          description: Method not allowed
          schema:
            type: string
      summary: Get user URLs in JSON format
  /ping:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "405":
          description: Method not allowed
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Ping database
swagger: "2.0"
