name: tests

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest
    container: golang:1.22

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: praktikum
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: >-
          go test -coverprofile=unit.coverage.out ./...
          bash < ( curl -Ls https://coverage.codacy.com/get.sh ) report \
              --force-coverage-parser go -r unit.coverage.out
        env:
          TEST_DATABASE_URI: "postgresql://postgres:postgres@postgres/praktikum?sslmode=disable"
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
